name: Board Game Gallery
favicon: null
layout_spectrum: 0.99819
typography_spectrum: 0.74789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030502'
    - '#dcf5f2'
    - '#2d603f'
    - '#72a07b'
    - '#94cfbd'
  brandStrength: 0.9289369492325932
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.7954487877432257
purpose: []
