name: Board Game Gallery
favicon: null
layout_spectrum: 0.99819
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffddb7'
    - '#834e2e'
    - '#b6995d'
    - '#1d58c0'
  brandStrength: 0.9289369492325932
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.7954487877432257
purpose: []
