name: Board Game Gallery
favicon: null
layout_spectrum: 0.99819
typography_spectrum: 0.3917114669457078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9289369492325932
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.7954487877432257
purpose: []
